sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  include:
    - node_js: "7"
      env: TEST_SUITE=standard
    - node_js: "7"
      env: TEST_SUITE=coveralls
env:
  - TEST_SUITE=coveralls
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
